# Site settings
name: RuoNan Blog
email: 2849@qq.com
author: RuoNan
url: http://www.ruonanbaby.com
resume_site: http://www.ruonanbaby.com
github: https://github.com/RuoNanBaby/
baseurl: ""
description: 所思即所想，所写即所思
meta_description: RuoNan;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: RuoNanBaby

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
